Finished try-on ui
zdd0419/MakeupBeauty pull request #14
Opened 2021-12-15 14:47 UTC by zrpxx

2021-12-15 16:48 UTC, wmn-231314 approved these changes
见下一条

2021-12-15 17:04 UTC, wmn-231314 requested changes
@zrpxx 重复点击时会出现圆形图片和方形图片随机切换的问题
TODO: 首页进入时的相应跳转

2021-12-16 04:44 UTC, zrpxx commented
添加了主界面跳转；
图片圆角问题怀疑是第三方库bug，尝试修复未果。

2021-12-16 04:48 UTC, zrpxx commented
第三方库圆角bug已有相关issue反馈。
https://github.com/shehuan/NiceImageView/issues/27

2021-12-16 04:54 UTC, zrpxx commented
根据相关issue修复了圆角问题。
https://github.com/shehuan/NiceImageView/issues/22

2021-12-16 05:24 UTC, wmn-231314 approved these changes
未发现问题

2021-12-16 05:30 UTC, merged