新增搜索页面，搜索结果页面
zdd0419/MakeupBeauty pull request #15
Opened 2021-12-17 11:55 UTC by dada1919

2021-12-17 14:39 UTC, zrpxx commented
@dada1919 未发现严重问题，解决与主分支冲突后合并

2021-12-18 03:05 UTC, wmn-231314 approved these changes, later dismissed
未发现问题

2021-12-18 03:13 UTC, wmn-231314 requested changes
@dada1919 冲突解决出现问题
AndroidManifest.xml 和DemoDataProvider.kt 出现语法错误
请重新修改冲突

2021-12-18 03:23 UTC, wmn-231314 commented on app/src/main/AndroidManifest.xml
>              android:name=".TryOn.TryOn"
<activity

2021-12-18 03:36 UTC, wmn-231314 approved these changes, later dismissed
未发现问题

2021-12-18 04:43 UTC, zrpxx reviewed
Fixed conflicts

2021-12-18 04:44 UTC, zrpxx approved these changes
Approved

2021-12-18 04:44 UTC, merged